### ISSUE TITLE
How to make robocup2d environment deterministic?

### ISSUE THREAD

**Issue by CoolPhilChen** [robocup2d/manual#5]
Hi @herodrigues ! Thanks very much for your manual! I want to remove the randomness of the robocup2d environment. Do you know if there is any way to do it?

**Comment by herodrigues** [comment]
Try `rcssserver -h` (or --help).

You will see a bunch of flags that you can change.

Also, there's a configuration file for server and player in `~/.rcssserver`

**Comment by CoolPhilChen** [comment]
great! thanks a lot! @herodrigues
